SistemaDeContabilidadGeneral/modulo_costo/urls.py
from django.urls import path
from .views import *


app_name='modulo_costo'

urlpatterns = [
    path('inicio_costos',Inicio.as_view(), name="inicio_costos"),
    path('agregar_proyecto/',proyectoPost.as_view(),name="agregar_proyecto"),
    #path('control_costos/',controlCostos,name="control_costos"),
    path('control_costos/',controlCostos,name="control_costos"),
    path('agregar_hoja_mano_obra/',hoja_mano_obraPost.as_view(),name="agregar_hoja_mano_obra"),
]

SistemaDeContabilidadGeneral/modulo_general/urls.py
from django.urls import path
from .views import *


app_name='modulo_general'

urlpatterns = [
    path('',Inicio.as_view(), name="mostrar_inicio"),
    path('partida_diario/', LibroDiario.as_view(), name="mostrar_partida_diario"),
    path('libro_mayor/', LibroMayor.as_view(), name="libro_mayor"),
    path('control-mayorizacion/',control_mayorizacion,name="control-mayorizacion"),
    path('partida/',PartidaFilterView.as_view(),name="partida"),
    path('mostrar_libro_mayor/<int:id_libro_mayor>',mostrar_libro_mayor,name="mostrar_libro_mayor"),
    path('balance_comprobacion/', BalanceComprobacion.as_view(),name="balance_comprobacion"),
    path('ajustar_balance/',ajustar_balance,name="ajustar_balance"),
    path('lista-estado-resultados',EstadoDeResultadoVista.as_view(),name="lista-estado-resultado"),
    path('lista-estado-capital',VistaEstadoCapital.as_view(),name="lista-estado-capital"),
    path('lista-balance-general',VistaBalanceGeneral.as_view(),name="lista-balance-general"),
]

SistemaDeContabilidadGeneral/scg_22/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('modulo_general.urls')),
    path('',include('modulo_costo.urls')),
]+ static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)

urlpatterns += static(settings.MEDIA_URL, document_root= settings.STATIC_ROOT) 

SistemaDeContabilidadGeneral/modulo_general/forms.py
from dataclasses import field
from pyexpat import model
from django import forms

from modulo_general.models import Registro

class PartidaDiarioForm(forms.ModelForm):
    class Meta:
        model = Registro
        fields = [
            'monto',
            'tipo_registro',
            'cuenta',
        ]
        labels = {
            'monto': 'Monto',
            'tipo_registro': 'Tipo de Registro',
            'cuenta': 'Cuenta',
        }
        widgets = {
            'monto': forms.TextInput(attrs={'class': 'form-control'}),
            'tipo_registro': forms.Select(attrs={'class': 'form-control'}),
            'cuenta': forms.Select(attrs={'class': 'form-control'}),
        }

class LibroMayor():
    pass

SistemaDeContabilidadGeneral/modulo_general/views.py
import json
from datetime import date, datetime, timedelta
from django.shortcuts import redirect, render, reverse
from django.test import TransactionTestCase
from modulo_general.forms import PartidaDiarioForm
from modulo_general.models import *
from django_filters.views import FilterView
from modulo_general.partidasFilter import PartidaListaFilter
import modulo_general.models as modelo
#libreria para trabajar con vistas basadas en clases
from django.views.generic import View, TemplateView

# Create your views here.

class Inicio(TemplateView):
    #cuando no se mandan parametros a la redifinicion de get
    # se tienen que pasar los parametros como se muestran 
    #en la firma de la función abaja
    template_name= 'modulo_general/index.html'


#clase temporal para guardara los registros de las cuentas T
class CuentatTemporal():
    def __init__(self,transacciones,saldo_cuenta_t,nombre_cuenta) -> None:
        self.transacciones=transacciones
        self.saldo_cuenta_t= saldo_cuenta_t
        self.nombre_cuenta= nombre_cuenta

#=======================================#

#funcion que obtiene el id de un libro mayor y muestar la informacion relacionada con el#
def mostrar_libro_mayor(request,id_libro_mayor):
    libro_mayor= modelo.LibroMayor.objects.get(id_libro_mayor=int(id_libro_mayor))
    cuentasT_del_libro= CuentaT.objects.filter(libro_mayor=libro_mayor.id_libro_mayor)
    cuentas_T=[]
    print(cuentasT_del_libro)
    for cuenta_T in cuentasT_del_libro :
        cuentas_T.append(CuentatTemporal(Registro.objects.filter(libro_mayor=cuenta_T.id_cuenta_T),cuenta_T.saldo_cuenta_T,cuenta_T.cuenta.nombre_cuenta))
    contexto={"registros_cuenta_t":cuentas_T,'id_libro_mayor':libro_mayor.id_libro_mayor}
    return render(request,'modulo_general/vista-libro-mayor.html',contexto)



class LibroMayor(View):
    def get(self,request,*args,**kwargs):
        libros_mayores= modelo.LibroMayor.objects.all()    
        return render(request,'modulo_general/libro_mayor.html',{'libros':libros_mayores})
    

    def post(self,request,*args,**kwargs):
        fecha_inicio= request.POST.get("fecha_inicio","no estaba la fecha de inicio")
        fecha_fin= request.POST.get("fecha_fin","no estaba la fecha de fin")
        partidas_del_periodo=self.obtener_partidas_periodo(fecha_inicio,fecha_fin)
        registros_del_periodo= self.obtener_registros(partidas_del_periodo)
        self.mayorizar(registros_del_periodo, fecha_inicio, fecha_fin)
        #contexto={'fecha_inicio':fecha_inicio,'fecha_fin':fecha_fin}
        #return render(request,"modulo_general/mayorizacion.html",contexto)
        return redirect('modulo_general:libro_mayor')


    def obtener_partidas_periodo(self,fecha_inicio,fecha_fin):
        print(fecha_inicio)
        print(fecha_fin)
        dt_inicial= datetime.strptime(fecha_inicio,'%Y-%m-%d')
        dt_final= datetime.strptime(fecha_fin,'%Y-%m-%d')
        dia= timedelta(1)
        registro_partidas=Partida.objects.filter(fecha_partida__range=[dt_inicial-dia,dt_final+dia])
        return registro_partidas

    def obtener_registros(self,registros_partidas):
        id_registro_partidas=[]
        registros_del_periodo={}
        registro_por_cuenta=[]
        registro_por_partida=[]
        transacciones= Registro.objects.all();
        cuentas=Cuenta.objects.all()
        for partida in registros_partidas:
            id_registro_partidas.append(partida.id_partida)
        for idpartida in id_registro_partidas:
            registro_por_partida.append(Registro.objects.filter(partida=idpartida))
        for cuenta in cuentas:
            for registro in registro_por_partida:
                temp_registro= registro.filter(cuenta=cuenta.id_cuenta)
                if temp_registro.exists():
                    registro_por_cuenta.append(temp_registro)
            if registro_por_cuenta:
                registros_del_periodo[str(cuenta.nombre_cuenta)]=registro_por_cuenta
            registro_por_cuenta=[]
        return registros_del_periodo


    def obtener_saldo_cuenta_deudora(self,registro):
        if registro.tipo_registro.nombre_tipo_registro=="Debe":
            return registro.monto
        elif registro.tipo_registro.nombre_tipo_registro=="Haber":
            return registro.monto*-1

    def obtener_saldo_cuenta_acreedora(self,registro):
        if registro.tipo_registro.nombre_tipo_registro=="Debe":
            return registro.monto*-1
        elif registro.tipo_registro.nombre_tipo_registro=="Haber":
            return registro.monto

    def mayorizar(self,registros_del_periodo,fecha_inicio,fecha_fin):
        cuentas= Cuenta.objects.all()
        temp_saldo=0
        libro_mayor= self.crear_libro_mayor(fecha_inicio,fecha_fin)
        print("Los registros del periodo son: {}".format(registros_del_periodo))
        for cuenta in cuentas:
            temp_registros = registros_del_periodo.get(cuenta.nombre_cuenta,"")
            if temp_registros!= "":
                temp_cuenta_t = CuentaT(saldo_cuenta_T=temp_saldo,libro_mayor=libro_mayor,cuenta=cuenta)
                temp_cuenta_t.save()
                for query_registro in temp_registros:
                    for transaccion in query_registro:
                        clase_cuenta = transaccion.cuenta.grupo_cuenta.clase_cuenta.nombre_clase_cuenta
                        if transaccion.cuenta.grupo_cuenta.clase_cuenta.nombre_clase_cuenta=="Activo" or transaccion.cuenta.grupo_cuenta.clase_cuenta.nombre_clase_cuenta=="Cuentas de resultado deudor":
                            temp_saldo+= self.obtener_saldo_cuenta_deudora(transaccion)
                        elif clase_cuenta == "Pasivo" or clase_cuenta=="Cuentas de resultado acreedor" or clase_cuenta=="Capital":
                            temp_saldo+= self.obtener_saldo_cuenta_acreedora(transaccion)
                        transaccion.libro_mayor=temp_cuenta_t
                        #este save daba error en las fechas tambien creo =D
                        transaccion.save()
                temp_cuenta_t.saldo_cuenta_T=temp_saldo
                temp_cuenta_t.save()
                temp_saldo=0
                temp_cuenta_t=None

    def crear_libro_mayor(self,fecha_inicio,fecha_fin):
        dt_inicio= datetime.strptime(fecha_inicio,"%Y-%m-%d")
        dt_fin= datetime.strptime(fecha_fin,"%Y-%m-%d")
        libro_mayor= modelo.LibroMayor(fecha_de_inicio_periodo=dt_inicio,fecha_fin_periodo=dt_fin)
        libro_mayor.save()
        return libro_mayor

    #cambiar la evaluacion de los if dependiendo del nombre de las clases de las cuentas
    def evaluar_saldo_registro(self,transaccion):
        clase_cuenta = transaccion.cuenta.grupo_cuenta.clase_cuenta.nombre_clase_cuenta
        if transaccion.cuenta.grupo_cuenta.clase_cuenta.nombre_clase_cuenta=="Activo" or transaccion.cuenta.grupo_cuenta.clase_cuenta.nombre_clase_cuenta=="Cuentas de resultado deudor":
            return self.obtener_saldo_cuenta_deudora(transaccion)
        elif clase_cuenta == "Pasivo" or clase_cuenta=="Cuentas de resultado acreedor" or clase_cuenta=="Capital":
            return self.obtener_saldo_cuenta_acreedora(transaccion)
            


    #Balance de comprobacion#


        #===================libro diario=================0#
class LibroDiario(View):
    lista_cuentas= Cuenta.objects.all()
    lista_tipo_movimiento= TipoRegistro.objects.all()
    contexto={'cuentas':lista_cuentas,'movimientos':lista_tipo_movimiento} 

    def get(self,request,*args,**kwargs):
        for arg in args:
            print(arg)
        return render(request,'modulo_general/registro_diario.html',self.contexto)

    def post(self,request,*args,**kwargs):
        json_data=json.loads(request.body)
        es_partida_ajuste=False
        #numero_partida= json_data[""]
        print("El valor del body es: {}".format(json_data))
        descripcion_partida=json_data["descripcionPartida"]
        numero_partida= json_data["numeroPartida"]
        registros= json_data["registros"]
        #creacion de la partida para el ejercicio
        partida= self.crear_partida(descripcion_partida,numero_partida,es_partida_ajuste)
        print("si llegamos al metodo para crear la partida")
        #asi sacamos los valores del objeto json
        for valores in registros:
            monto=valores["monto"]
            monto= self.obtenerMontoTransaccion(monto)
            cuenta=valores["cuenta"]
            tempCuenta=Cuenta.objects.get(nombre_cuenta=cuenta)
            tiporegistro=valores["tipoRegistro"]["nombreTipoRegistro"]
            temp_tipo_registro= TipoRegistro.objects.get(nombre_tipo_registro=tiporegistro)
            self.crear_registro(monto,partida,tempCuenta,temp_tipo_registro)
        return redirect('modulo_general:mostrar_inicio')

    def crear_partida(self,descripcion_partida,numero_partida,es_partida_ajuste):
        partida= Partida(fecha_partida=datetime.now(),descripcion_partida=descripcion_partida,numero_partida=numero_partida,es_partida_ajuste=es_partida_ajuste)
        partida.save()
        return partida
    def crear_registro(self,monto,partida,cuenta,tipoRegistro):
        registro=Registro(monto=monto,partida=partida,cuenta=cuenta,tipo_registro=tipoRegistro)
        registro.save()
    
    #convertir el numero que viene de la pantalla a valor normal
    def obtenerMontoTransaccion(self,numeroCadena):
        return float(numeroCadena.replace("$",""))




#==========Esto no lo vamo a ocupar===========#

def mostrar_partida_diario(request):
    registrodiario = Registro.objects.all()
    if request.method == 'POST':
        form = PartidaDiarioForm(request.POST)
        if form.is_valid():
            form.save()
        return redirect('../index')
    else:
        form = PartidaDiarioForm()
    form = PartidaDiarioForm()
    return render(request,'modulo_general/partida_diario.html',{'form':form,'registrodiario':registrodiario})

def control_mayorizacion(request):
        libro_mayor= LibroMayor()

SistemaDeContabilidadGeneral/modulo_general/templates/modulo_general/ajustar_balance.html
<!DOCTYPE html>
<html lang="en">
<head>
  {% load static %}
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <title>Paridas de ajuste</title>
</head>
<body>
    <div class="container">
        <form method="POST" id="formulario-registro-diario">
          {% csrf_token %}
            <div class="card">
              <div class="card-body">
                <div class="row">
                  <div class="col">
                    <label for="inputDate" class="form-label">Fecha</label>
                    <input type="text" class="form-control" id="idFecha">
                  </div>
                  <div class="col">
                    <label for="inputDescripcion" class="form-label">Numero de partida</label>
                    <input type="number" class="form-control" id="idNumero"  name="idNumero" pattern="[0-9]{1,10}">
                  </div>
                </div>

                <div class="mb-3">
                  <label for="inputDescripcion" class="form-label">Descripción</label>
                  <input type="text" class="form-control" id="idDescripcion" name="idDescripcion">
                </div>
                
                </div>    
            </div>
    

            <div class="card" style="margin-top: 10px;">
              <div class="card-body">

              <table class="table">
                <div class="row">
                    <div class="col">
                      <label for="cuentaLabel">Cuenta</label>
                      <select class="form-control" id="cuenta" name="cuenta">
                        {% if cuentas %}
                          {% for cuenta in cuentas %}
                          <option value="{{ cuenta.nombre_cuenta }}">{{cuenta.nombre_cuenta}}</option>
                          {% endfor %}
                        {% endif %}
                      </select>
                    </div>
                    <div class="col">
                      <label for="tipoMovimiento">Tipo Movimiento</label>
                      <select class="form-control" id="tipoMovimientoSelect" name="tipoMovimientoSelect">
                        {% if movimientos %}
                          {% for movimiento in movimientos%}
                          <option value="{{ movimiento.nombre_tipo_registro}}">{{movimiento.nombre_tipo_registro}}</option>    
                          {% endfor %}
                        {% endif %}
                      </select>
                    </div>
                  </div>
                  <div class="form-group">
                    <label for="montoInput">Monto transacción</label>
                    <input type="text" class="form-control" id="monto" name="monto" placeholder="Ingrese el monto de la transacción" pattern="[0-9]{1,5}.?[0-9]{0,2}">
                  </div>
              </table>
             
              
         <input type="button" class="btn btn-primary" value="Agregar" id="btnAgregar">     
        </div> 
      </div>  
        

      
    </div>
    <p></p>
    <div class="container">
        <table class="table" id="tablaRegistro">
            <thead class="thead-dark">
              <tr>
                <th scope="col">MONTO</th>
                <th scope="col">TIPO MOVIMIENTO</th>
                <th scope="col">CUENTA</th>
                <th scope="col">ACCIONES</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td class="montoElemento">{{ elemt.monto }}</td>
                <td class="tipoRegistroElemento">{{ elemt.tipo_registro }}</td>
                <td class="cuentaElemento">{{ elemt.cuenta }}</td>
              </tr>
            </tbody>
          </table>
          <input type="button" class="btn btn-primary" value="Guardar Partida" id="btnGuardar">     
    </div> 
</form> 
<a href="{% url 'modulo_general:balance_comprobacion'%}?ajustar_balance=ok" class="btn btn-success">Realizar Ajuste</a>

{% if exito %}

  <div class="alert alert-primary" role="alert">
  {{ exito }}
  </div>
{% endif %}

<script src="{% static 'modulo_general/js/ajustar_balance.js' %}"></script>
</body>
</html>

SistemaDeContabilidadGeneral/modulo_general/templates/modulo_general/balance-comprobacion.html
<!DOCTYPE html>
<html lang="en">
<head>
  {% load static %}
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css"/>
    <title>Balance de Comprobación</title>
</head>
<body>
    <div style="width: 75%; margin: 0 auto;">
        <table class="table">
            <thead>
                <tr style="text-align:center;">
                    <td colspan="4"><h3>5-State Tech</h3></td>
                </tr>
                <tr style="border: none; text-align: center;">
                    <td colspan="4"><h3>Balance de comprobacion</h3></td>
                </tr>
                <tr style="border: none; text-align: center;">
                    <td colspan="4">Periodo de {{temp_libro_mayor.fecha_de_inicio_periodo}} hasta {{temp_libro_mayor.fecha_fin_periodo}}</td>
                </tr>
              <tr>
                <th scope="col">Numero cuenta</th>
                <th scope="col">Nombre cuenta</th>
                <th scope="col">Debe</th>
                <th scope="col">Haber</th>
              </tr>
            </thead>
            <tbody>
              {% for cargos in cuentas_activo %}
              <tr>
                <th scope="row">{{cargos.cuenta.codigo_cuenta}}</th>
                <td>{{cargos.cuenta.nombre_cuenta}}</td>
                <td>{{cargos.saldo_cuenta_T}}</td>
                <td>$.-</td>
              </tr>
              {% endfor %}
              {% for abono in cuentas_pasivos_capital %}
              <tr>
                <th scope="row">{{abono.cuenta.codigo_cuenta}}</th>
                <td>{{abono.cuenta.nombre_cuenta}}</td>
                <td>$.-</td>
                <td>{{abono.saldo_cuenta_T}}</td>
              </tr>
              {% endfor %}
              <tfoot style="background-color: rgb(190, 186, 186);">
                <td colspan="2">Total</td>
                <td>{{saldo_debe}}</td>
                <td>{{saldo_haber}}</td>
              </tfoot>
            </tbody>
          </table>
          {% if balance_comprobacion %}
          {% if balance_comprobacion.esta_ajustado == False %}
          <a href="{% url 'modulo_general:ajustar_balance' %}" class="btn btn-success">Agregar partidas de ajuste</a>
          {% endif %}
          <a href="{% url 'modulo_general:lista-estado-resultado' %}?crear_estado={{balance_comprobacion.id}}" class="btn btn-success">Crear estado de resultado</a>
          <a href="{% url 'modulo_general:lista-estado-capital' %}?crear_estado={{balance_comprobacion.id}}" class="btn btn-success">Crear estado de capital</a>
          <a href="{% url 'modulo_general:lista-balance-general' %}?crear_balance={{balance_comprobacion.id}}" class="btn btn-success">Crear Balance General</a>
          {% endif %}
    </div>
    <script src="{% static 'modulo_general/js/corregir_cantidades.js' %}"></script>
</body>
</html>

SistemaDeContabilidadGeneral/modulo_general/templates/modulo_general/barra.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'modulo_general/css/barra.css' %}">
    <title>Document</title>
</head>
<body>
    <div class="container" style="padding-bottom: 10%;">
        <div class="fixed-nav-bar">
            <div class="logo" ><span>5º</span>State-Tech</div>
            <input type="checkbox" id="menuButton" />
            <label for="menuButton" class="menu-button-label">
                <div class="white-bar"></div>
                <div class="white-bar"></div>
                <div class="white-bar"></div>
                <div class="white-bar"></div>
            </label>
        </div>
        <div class="the-bass" style="max-height: 105px">
            <div class="rela-block drop-down-container">
                <div class="drop-down-item"><a href="{% url 'modulo_general:mostrar_inicio'%}" style="text-decoration: none; color: white;">Inicio</a></div>
            </div>
            <div class="rela-block drop-down-container">
                <div class="drop-down-item"><a href="{% url 'modulo_costo:inicio_costos'%}" style="text-decoration: none; color: white;">Gestion de costos</a></div>
            </div>
            </div>
        </div>
    </div>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="{% static 'modulo_general/js/barra.js' %}"></script>
</body>

</html>

SistemaDeContabilidadGeneral/modulo_general/templates/modulo_general/index.html
<!DOCTYPE html>
<html lang="en">

<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css"
        integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'modulo_general/static/css/index.css' %}">

    <title>Sistema Contable SCG_22</title>
</head>

<body>

    <header>
        <nav class="navbar text-white bg-dark">
            <h2>SCG_22</h2>
        </nav>
    </header>

    <main>

        <div class="container py-4">

            <div class="card mb-3">

                <div class="card-header">
                    <div class="text-center fs-2">
                        <h1>Inicio</h1>
                    </div>
                </div>

                <div class="card-body">

                    <div class="row row-cols-1 row-cols-md-3 g-4">
                        <div class="col">
                            <div class="card h-100">
                                <div class="card-body">
                                    <h5 class="card-title">Registrar partida diario</h5>
                                    <p class="card-text">Ingrese sus transacciones diarias !</p>
                                    <a href="{%url 'modulo_general:mostrar_partida_diario'%}" class="btn btn-dark">Registrar partidad e de diario</a>
                                </div>
                            </div>
                        </div>
                        <div class="col">
                            <div class="card h-100">
                                <div class="card-body">
                                    <h5 class="card-title">Ver listados de libro mayor</h5>
                                    <p class="card-text">Vea los libros que se han registrado</p>
                                    <a href="{%url 'modulo_general:libro_mayor'%}" class="btn btn-dark">ver libros mayores</a>
                                </div>
                            </div>
                        </div>
                        <div class="col">
                            <div class="card h-100">
                                <div class="card-body">
                                    <h5 class="card-title">Ver listados de Balances de comprobacion</h5>
                                    <p class="card-text">Cree o consulte los balances de comprobacion</p>
                                    <a href="{% url 'modulo_general:balance_comprobacion'%}" class="btn btn-dark">ver balances de comprobacion</a>
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="row row-cols-1 row-cols-md-3 g-4 py-4">
                        <div class="col">
                            <div class="card h-100">
                                <div class="card-body">
                                    <h5 class="card-title">Ver estados de resultado</h5>
                                    <p class="card-text">Consulte los estados de resultado</p>
                                    <a href="{%url 'modulo_general:lista-estado-resultado'%}" class="btn btn-dark">ver estados de resultado</a>
                                </div>
                            </div>
                        </div>
                        <div class="col">
                            <div class="card h-100">
                                <div class="card-body">
                                    <h5 class="card-title">Ver estado de capital</h5>
                                    <p class="card-text">Consulte los estados de comprobacion</p>
                                    <a href="{% url 'modulo_general:lista-estado-capital'%}" class="btn btn-dark">Ver estados de capital</a>
                                </div>
                            </div>
                        </div>
                        <div class="col">
                            <div class="card h-100">
                                <div class="card-body">
                                    <h5 class="card-title">Ver balances generales</h5>
                                    <p class="card-text">Consulte los balances generales/p>
                                    <a href="{% url 'modulo_general:lista-balance-general'%}" class="btn btn-dark">Balances generales</a>
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="row row-cols-1 row-cols-md-3 g-4">
                        <div class="col">
                            <div class="card h-100">
                                <div class="card-body">
                                    <h5 class="card-title">Registrar proyecto</h5>
                                    <p class="card-text">Ingres los datos de su proyecto</p>
                                    <a href="{% url 'modulo_costo:agregar_proyecto'%}" class="btn btn-dark">Registrar partida de de diario</a>
                                </div>
                            </div>
                        </div>
                        <div class="col">
                            <div class="card h-100">
                                <div class="card-body">
                                    <h5 class="card-title">Agregar hoja de mano de obra</h5>
                                    <p class="card-text">....</p>
                                    <a href="{% url 'modulo_costo:agregar_hoja_mano_obra'%}" class="btn btn-dark">Registrar Mano de obra</a>
                                </div>
                            </div>
                        </div>
                    </div>

                </div>

            </div>

        </div>

    </main>

    <footer class="pt-3 mt-4 text-muted border-top">
        &copy; 5State-Tech - SCG_22 - 2022
    </footer>

</body>

</html>

SistemaDeContabilidadGeneral/modulo_general/templates/modulo_general/mayorizacion.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css">
    <title>Document</title>
</head>
<body>
    {{fecha_inicio}}
    {{fecha_fin}}
</body>
</html>