SistemaDeContabilidadGeneral/modulo_costo/urls.py
from django.urls import path
from .views import *


app_name='modulo_costo'

urlpatterns = [
    path('inicio_costos',Inicio.as_view(), name="inicio_costos"),
    path('agregar_proyecto/',proyectoPost.as_view(),name="agregar_proyecto"),
    #path('control_costos/',controlCostos,name="control_costos"),
    path('control_costos/',controlCostos,name="control_costos"),
    path('agregar_hoja_mano_obra/',hoja_mano_obraPost.as_view(),name="agregar_hoja_mano_obra"),
]

SistemaDeContabilidadGeneral/scg_22/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('modulo_general.urls')),
    path('',include('modulo_costo.urls')),
]+ static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)

urlpatterns += static(settings.MEDIA_URL, document_root= settings.STATIC_ROOT) 

SistemaDeContabilidadGeneral/modulo_costo/models.py
from django.db import models

# Create your models here.
class Proyecto(models.Model):
    id_proyecto= models.AutoField(primary_key=True,unique=True,verbose_name="id_proyecto")
    nombre_proyecto= models.CharField(max_length=40,blank=False,null=False,verbose_name="nombre_proyecto")
    fecha_expedicion= models.DateField()
    departamento= models.CharField(max_length=40,blank=False,null=False,verbose_name="departamento")
    servicio= models.CharField(max_length=40,blank=False,null=False,verbose_name="servicio")
    presupuesto_cliente= models.FloatField(verbose_name="presupuesto_cliente")
    numero_orden= models.IntegerField(null=True,blank=True)
    descripcion= models.TextField(max_length=200,blank=True,null=True,verbose_name="descripcion")
    #relaciones
    id_costos_indirectos= models.ForeignKey('CostosIndirectos',on_delete=models.CASCADE,verbose_name="id_costos_indirectos")

    def __str__(self):
        return self.nombre_proyecto

class CostosIndirectos(models.Model):
    id_costos_indirectos= models.AutoField(primary_key=True,unique=True,verbose_name="id_costos_indirectos")
    tasa_costo_indirecto= models.FloatField(verbose_name="tasa_costo_indirecto")
    descripcion_tasa_indirecta = models.CharField(max_length=50, blank= True, null = True)
    #relaciones
    #id_proyecto= models.ForeignKey('Proyecto',on_delete=models.CASCADE,verbose_name="id_proyecto")
    def __str__(self):
        return self.tasa_costo_indirecto.__str__()+" "+self.descripcion_tasa_indirecta

class hoja_mano_obra(models.Model):
    id_hoja_mano_obra= models.AutoField(primary_key=True,unique=True,verbose_name="id_hoja_mano_obra")
    nombre_cargo= models.CharField(max_length=40,blank=False,null=False,verbose_name="nombre_cargo")
    cantidad_cargo= models.IntegerField(verbose_name="cantidad_cargo",null=True,blank=True)
    numero_hora= models.FloatField(verbose_name="salario_cargo",null=True,blank=True)
    salario_hora= models.FloatField(verbose_name="salario_hora",null=True,blank=True)
    es_costo_real = models.BooleanField(verbose_name = "es_costo_real")

    #relaciones
    id_proyecto= models.ForeignKey('Proyecto',on_delete=models.CASCADE,verbose_name="id_proyecto")
    def __str__(self):
        return self.nombre_cargo

SistemaDeContabilidadGeneral/modulo_costo/forms.py
from django import forms
from modulo_costo.models import *

class ProyectoForm(forms.ModelForm):
    class Meta:
        model = Proyecto
        fields = [
            'nombre_proyecto',
            'fecha_expedicion',
            'departamento',
            'servicio',
            'presupuesto_cliente',
            'numero_orden',
            'descripcion',
            #'id_hoja_mano_obra',
            'id_costos_indirectos',
        ]
        labels = {
            'nombre_proyecto': 'Nombre del Proyecto',
            'fecha_expedicion': 'Fecha de Expedicion',
            'departamento': 'Departamento',
            'servicio': 'Servicio',
            'presupuesto_cliente': 'Presupuesto del Cliente',
            'numero_orden': 'Numero de Orden',
            'descripcion': 'Descripcion',
            #'id_hoja_mano_obra': 'Hoja de Mano de Obra',
            'id_costos_indirectos': 'Costos Indirectos',
        }
        widgets = {
            'nombre_proyecto': forms.TextInput(attrs={'class': 'form-control'}),
            'fecha_expedicion': forms.DateInput(attrs={'class': 'form-control'}),
            'departamento': forms.TextInput(attrs={'class': 'form-control'}),
            'servicio': forms.TextInput(attrs={'class': 'form-control'}),
            'presupuesto_cliente': forms.TextInput(attrs={'class': 'form-control'}),
            'numero_orden': forms.TextInput(attrs={'class': 'form-control'}),
            'descripcion': forms.TextInput(attrs={'class': 'form-control'}),
            #'id_hoja_mano_obra': forms.Select(attrs={'class': 'form-control'}),
            'id_costos_indirectos': forms.Select(attrs={'class': 'form-control'}),
        }

class CostosIndirectosForm(forms.ModelForm):
    class Meta:
        model = CostosIndirectos
        fields = [
            'tasa_costo_indirecto',
            #'id_proyecto',
        ]
        labels = {
            'tasa_costo_indirecto': 'Tasa de Costo Indirecto',
            #'id_proyecto': 'Proyecto',
        }
        widgets = {
            'tasa_costo_indirecto': forms.TextInput(attrs={'class': 'form-control'}),
            #'id_proyecto': forms.Select(attrs={'class': 'form-control'}),
        }

class HojaManoObraForm(forms.ModelForm):
    class Meta:
        model = hoja_mano_obra
        fields = [
            'id_proyecto',
            'nombre_cargo',
            'cantidad_cargo',
            'numero_hora',
            'salario_hora', 
        ]
        labels = {
            'id_proyecto': 'Proyecto',
            'nombre_cargo': 'Nombre del Cargo',
            'cantidad_cargo': 'Cantidad del Cargo',
            'numero_hora': 'Numero de Horas',
            'salario_hora': 'Salario por Hora',
        }
        widgets = {
            'id_proyecto': forms.Select(attrs={'class': 'form-control'}),
            'nombre_cargo': forms.TextInput(attrs={'class': 'form-control'}),
            'cantidad_cargo': forms.TextInput(attrs={'class': 'form-control'}),
            'numero_hora': forms.TextInput(attrs={'class': 'form-control'}),
            'salario_hora': forms.TextInput(attrs={'class': 'form-control'}),
        }

SistemaDeContabilidadGeneral/modulo_costo/views.py
from time import process_time_ns
from django.shortcuts import render
from django.views.generic import TemplateView, ListView, CreateView
from django.urls import reverse_lazy
from .models import *
from .forms import *

# Create your views here.

class Inicio(ListView):
    model = Proyecto
    template_name= 'index.html'
    context_object_name = 'proyectos'

class proyectoPost(CreateView):
    template_name = 'registro_proyecto.html'
    model = Proyecto
    form_class = ProyectoForm
    success_url = reverse_lazy('modulo_costo:inicio_costos')


#definir funcion que reciba el id del proyecto renderice el template y mande el objeto proyecto
def controlCostos(request):
    pk = request.GET.get('pk', "")
    if pk!="":
        proyecto = Proyecto.objects.get(id_proyecto=int(pk))
        hoja_costos= hoja_mano_obra.objects.filter(id_proyecto=int(pk))
        tasa_del_proyecto = proyecto.id_costos_indirectos.tasa_costo_indirecto
        descripion_tasa = proyecto.id_costos_indirectos.descripcion_tasa_indirecta
        longitud_hoja_costos =  len(hoja_costos)
        costo_total_cif =  0
        
        for hoja in hoja_costos:
            print(hoja.cantidad_cargo)
            print(hoja.numero_hora)
            costo_total_cif+= hoja.cantidad_cargo*hoja.numero_hora*hoja.salario_hora
        total_importe_cif = tasa_del_proyecto * costo_total_cif
        #costos_indirectos= CostosIndirectos.objects.filter(id_proyecto=pk)
        return render(request, 'control_costos.html', {'proyecto': proyecto, 'hoja_costos': hoja_costos,'tasa': tasa_del_proyecto,'longitud' : longitud_hoja_costos,'costo_total':costo_total_cif,"importe_cif":total_importe_cif,"descripcion":descripion_tasa})


class hoja_mano_obraPost(CreateView):
    template_name = 'agregar_hoja_mano_obra.html'
    model = hoja_mano_obra
    form_class = HojaManoObraForm
    success_url = reverse_lazy('modulo_costo:inicio_costos')

SistemaDeContabilidadGeneral/modulo_costo/templates/agregar_hoja_mano_obra.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css">
    <title>Document</title>
</head>
<body>
    <form method="post">
    <div class="container">
        <h1 style="align-items: center;">Agregar mano de obra</h1>
        <form method="post">
            {% csrf_token %}
            {{ form }}
            <!-- centrar el botton -->
            
    </div>
    <div class="row justify-content-center" style="padding-top: 5%;">
        <div class="col-sm-4"> 
            <button type="submit" class="btn btn-primary">Guardar</button>
            <a class="btn btn-primary" href="{% url 'modulo_costo:inicio_costos' %}">Volver</a>
        </div>
    </div>
</form>
    
</body>
</html>

SistemaDeContabilidadGeneral/modulo_costo/templates/control_costos.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css"
        integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <title>Control de Costos</title>
</head>

<body>

    <h1 class="text-center py-4">Control de costos</h1>

    <div class="container">
        <div class="row justify-content-start">
            <div class="col-sm-3">
                <label class="label">
                    <h5>Proyecto: </h5>
                </label>                
            </div>            
            <div class="col-sm-3">
                    {{ proyecto.nombre_proyecto }}
            </div>            
        </div>
        <div class="row justify-content-start">
            <div class="col-sm-3">
                <label class="label">
                    <h5>Fecha de expedición: </h5>
                </label>                
            </div>            
            <div class="col-sm-3">
                    {{ proyecto.fecha_expedicion }}
            </div>            
        </div>
        <div class="row justify-content-start">
            <div class="col-sm-3">
                <label class="label">
                    <h5>Departamento: </h5>
                </label>                
            </div>            
            <div class="col-sm-3">
                    {{ proyecto.departamento }}
            </div>            
        </div>
        <div class="row justify-content-start">
            <div class="col-sm-3">
                <label class="label">
                    <h5>Servicio: </h5>
                </label>                
            </div>            
            <div class="col-sm-3">
                    {{ proyecto.servicio }}
            </div>            
        </div>
        <br>

        <table class="table table-bordered">
            <thead class="thead-dark">
                <tr>
                    <th colspan="5" class="table-active text-center">Mano de obra</th>
                </tr>
                <tr>                    
                    <th scope="col" class="text-center">Cargo</th>
                    <th scope="col" class="text-center"># Empleados</th>
                    <th scope="col" class="text-center">Hora</th>
                    <th scope="col" class="text-center"># Hora</th>
                    <th scope="col" class="text-center">Total</th>
                </tr>
            </thead>
            <tbody>
                {% for costo in hoja_costos %}
                <tr>
                    <td>{{ costo.nombre_cargo }}</td>
                    <td>{{ costo.cantidad_cargo }}</td>
                    <td>{{ costo.salario_hora }}</td>
                    <td>{{ costo.numero_hora }}</td>
                    <td>{{costo_total}}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
        <table class="table table-bordered">
            <thead class="thead-dark">
                <tr>
                    <th colspan="2" class="table-active text-center">CIF</th>
                </tr> 
                <tr>
                    <th scope="col" class="text-center">Tasa</th>
                    <th scope="col" class="text-center">Total importe cif</th>
                </tr>
            </thead>
                <tr>
                    <td>{{ tasa }}  {{descripcion}}</td>
                    <td> {{importe_cif}} </td>
                </tr>
        </table>

        <div class="py-4">
            <a class="btn btn-primary" href="{% url 'modulo_costo:inicio_costos' %}">Volver</a>
            <a class="btn btn-primary" href="{% url 'modulo_costo:agregar_hoja_mano_obra' %}">Agregar mano de obra</a>
        </div>

    </div>

</body>

</html>

SistemaDeContabilidadGeneral/modulo_costo/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css">
    <title>Document</title>
</head>
<body>
    <div class="container" style="padding-top: 3%;">
        <div class="row">
            <div class="col-md-12">
                <h1>Centro de gestion de costos</h1>
                <a class="btn btn-primary" href="{% url 'modulo_costo:agregar_proyecto' %}">Agregar Proyecto</a>
            </div>
        </div>
    </div>

    <div class="container" style="padding-top: 3%;">
        <div class="row">
            {% for proyecto in proyectos %}
          <div class="col-sm" style="padding-top: 3%;">
            <div class="card" style="height: 15rem;">
                <div class="card-body">
                    <h5 class="card-title">{{proyecto.nombre_proyecto}} </h5>
                    <a href="{% url 'modulo_costo:control_costos' %}?pk={{proyecto.id_proyecto}}" class="btn btn-primary">Ir a costeo</a>
                    <p class="card-text">{{proyecto.descripcion}}</p>
                    <!-- alinear elemento en al final -->
                </div>
            </div>
          </div>
          {% endfor %}
        </div>
      </div>
   

      
</body>
</html>

SistemaDeContabilidadGeneral/modulo_costo/templates/registro_proyecto.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css">
    <title>Document</title>
</head>
<body>
    <div class="container">
        <div class="row justify-content-center" style="padding-top: 5%;">
            <div class="col-sm-4"> 
                <h1>Ingresar Proyecto</h1>
            </div>
        </div>
    </div>
    <div class="container">
        <form method="POST">
            {% csrf_token %}
            <div class="container">
                <div class="card">
                    <div class="card-header">
                      Datos del proyecto
                    </div>
                    <div class="card-body">
                        <div class="container" style="padding-top: 5%;">
                            <div class="row ">
                                <label>{{ form.nombre_proyecto.label }}: </label> 
                                <div class="col">
                                    {{ form.nombre_proyecto }}
                                </div>
                                <label>Fecha Inicio: </label> 
                                <div class="col">
                                    {{form.fecha_expedicion}}
                                </div>

                            </div>
                            <div class="row" style="padding-top: 1%;">
                                <label>Servicio: </label> 
                                <div class="col-sm">
                                    {{ form.servicio }}
                                </div>
                                <label>Numero de orden: </label> 
                                <div class="col-sm">
                                    {{form.numero_orden}}   
                                </div>
                        </div>
                    </div>
                </div>
            </div>

            
            <div class="container" style="padding-top: 3%;">
                <div class="card">
                    <div class="card-header">
                      Datos del cliente
                    </div>
                    <div class="card-body">
                        <div class="container" style="padding-top: 5%;">
                            <div class="row">
 
                                <label>Presupuesto del Cliente: </label> 
                                <div class="col-sm">
                                    {{form.presupuesto_cliente}}  
                                </div>
                                <label>Direccion: </label>
                                <div class="col">
                                    {{form.departamento}}    
                                </div>

                            </div>
                        </div>
                    </div>
                  </div>
            </div>
            
            <div class="container" style="padding-top: 3%;">
                <div class="card">
                    <div class="card-header">
                      Detalles
                    </div>
                    <div class="card-body">
                      <div class="container" style="padding-top: 5%;">
                        <div class="row">
                            <label>Descripcion: </label> 
                            <div class="col-sm-4">
                                {{ form.descripcion }}
                            </div>
                            <label>Seleccionar taza: </label>
                            <div class="col-sm">
                                {{form.id_costos_indirectos}}    
                            </div>
                        </div>
                    </div>
                    </div>
                  </div>
    
            </div>
            
            
            <div class="row" style="padding-top: 5%;">
                <div class="col-sm-4"> 
                    <a class="btn btn-primary" href="{% url 'modulo_costo:inicio_costos' %}">Volver</a>
                    <button type="submit" class="btn btn-primary">Guardar</button>
                </div>
            </div>
        </form>        
    </div>

</body>
</html>