SistemaDeControlAduanero/gestionTransporte/urls.py
from django.urls import path, re_path
from .views import *
from django.contrib.auth import views
app_name="gestionTransporte"

urlpatterns = [
    path('index/', index, name="index"),
    path('registrarVehiculo/', registrarVehiculo, name="registrarVehiculo"),
    path('eliminarVehiculo/<id>',eliminarVehiculo),
    path('edicionVehiculo/<id>',edicionVehiculo),
    path('editarVehiculo/', editarVehiculo),
    path('registrarMotorista/', registrarMotorista,name="registrarMotorista"),
    path('eliminarMotorista/<id>',eliminarMotorista),
    path('edicionMotorista/<id>',edicionMotorista),
    path('editarMotorista/', editarMotorista),
    path('registroManifiesto/',registrarManifiestoCarga, name="registroManifiesto"),
    path('registrarEmpresa/', registrarEmpresa,name="registrarEmpresa"),
    path('registroUsuario/',registrarUsuario, name="registroUsuario"),
    path('empresa_home/',mostrar_inicio_empresa, name="inicioEmpresa"),
    path('login/',iniciar_sesion, name="iniciar_sesion"),
    path('logout/',realizar_logout, name="logout_sesion"),
    path('accounts/login/', iniciar_sesion, name='login_autenticacion'),
    path('modal_registro/',ver_modal,name="ver_modal"),
    path('listadoRegistroTransporte/<int:id_aduana>', trasnporte_list, name='trasnporte_list'),
    path('detalle_validacion/<int:id_validacion>',agregar_detalles_validacion,name="agregar_detalles_validacion"),
    path('eliminar_observacion/<int:id_detalle>',eliminar_observacion,name="eliminar_observacion"),
    path('inicioEmpresa/', inicioEmpresa, name="inicioEmpresa"),
    path('inicioAdministrador/', inicioAdministrador, name="inicioAdministrador"),
    path('verRegistroTransito/<id>', verRegistroTransito, name='verRegistroTransito'),
    path('inicioAdministrador/', inicioAdministrador, name="inicioAdministrador"),
    path('gestionAduana/', gestionAduana, name="gestionAduana"),
    ]

SistemaDeControlAduanero/scta_g16/urls.py
from os import stat
from django.contrib import admin

from django.conf import settings
from django.conf.urls.static import static

from django.urls import path, include
from scta_g16.views import prueba

urlpatterns = [
    path('admin/', admin.site.urls),
    path('prueba/', prueba),
    path('',include('gestionTransporte.urls'))
]+static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)

urlpatterns+= static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

SistemaDeControlAduanero/gestionTransporte/models.py
from pyexpat import model
from django.db import models
from django.contrib.auth.models import AbstractUser
from .manager import UserManager

#tipo usuario ¿empresa  ---- aduana?

# Create your models here.
class TipoDocumento(models.Model):
    tipo_documento= models.CharField(max_length=50)
    
    def __str__(self) -> str:
        return "{}".format(self.tipo_documento)

class Sexo(models.Model):
    nombre_sexo=models.CharField(max_length=30)

    def __str__(self) -> str:
        return "{}".format(self.nombre_sexo)

class UsuarioSistema(AbstractUser):
    rol = models.CharField(max_length=15)
    REQUIRED_FIELDS=['email']

class Departamento(models.Model):
    codigo_departamento= models.CharField(max_length=2, primary_key=True)
    nombre_departamento= models.CharField(max_length=100)

class Municipio(models.Model):
    departamento= models.ForeignKey(Departamento, on_delete=models.PROTECT)
    codigo_municipio= models.CharField(max_length=4, primary_key=True)
    nombre_municipio= models.CharField(max_length=100)

    def __str__(self) -> str:
        return "{}".format(self.nombre_municipio)

class Pais(models.Model):
    nombre_pais=models.CharField(max_length=75)

    def __str__(self) -> str:
        return "{}".format(self.nombre_pais)
    
class Aduana(models.Model):
    nombre = models.CharField(max_length=30)
    direccion = models.CharField(max_length=70)
    municipio= models.ForeignKey(Municipio,on_delete=models.PROTECT)
    usuario_sistema = models.ManyToManyField(UsuarioSistema)

    def __str__(self) -> str:
        return "{}".format(self.nombre)

class Empresa(models.Model):
    nit = models.CharField(max_length=15)
    nombre = models.CharField(max_length=30)
    correo = models.EmailField()
    direccion = models.CharField(max_length=70)
    telefono = models.CharField(max_length=15)
    pais = models.ForeignKey(Pais, on_delete=models.PROTECT, null=True)
    rubro = models.CharField(max_length=30)
    usuario_sistema = models.OneToOneField(UsuarioSistema,on_delete=models.CASCADE)
    tipo_documento_empresa= models.ForeignKey(TipoDocumento,on_delete=models.PROTECT)

    def __str__(self) -> str:
        return "{}".format(self.nombre)

class Motorista(models.Model):
    nombre = models.CharField(max_length=30)
    apellido = models.CharField(max_length=30)
    doc_identificacion = models.CharField(max_length=30)
    licencia = models.CharField(max_length=30)
    sexo = models.CharField(max_length=30)
    nombre = models.CharField(max_length=30)
    estado_motorista= models.BooleanField(default=True)
    empresa = models.ForeignKey(Empresa, on_delete=models.CASCADE)
    sexo= models.ForeignKey(Sexo, on_delete=models.PROTECT)

    def __str__(self) -> str:
        return "{}, Licencia: {}".format(self.nombre,self.licencia)

class Vehiculo(models.Model):
    marca = models.CharField(max_length=30)
    modelo = models.CharField(max_length=30)
    placa = models.CharField(max_length=30)
    anio = models.IntegerField()
    motor = models.CharField(max_length=30)
    chasis = models.CharField(max_length=30)
    num_ejes = models.IntegerField()
    capacidad = models.DecimalField(max_digits=10, decimal_places=2)
    estado = models.BooleanField(default=True)
    empresa = models.ForeignKey(Empresa, on_delete=models.CASCADE)

    def __str__(self) -> str:
        return "{}".format(self.placa)

class Carga(models.Model):
    tipo = models.CharField(max_length=30)
    descripcion = models.CharField(max_length=250)
    peso = models.DecimalField(max_digits=10,decimal_places=2)

    def __str__(self) -> str:
        return "{}, {} kg".format(self.tipo,self.peso)

class RegistroTransito(models.Model):
    numero_registro = models.IntegerField()
    origen = models.CharField(max_length=150)
    pais_consignatario = models.ForeignKey(Pais, on_delete=models.PROTECT)
    fecha_registro = models.DateField(auto_now_add=True)
    fecha_destino = models.DateField()
    motorista = models.ForeignKey(Motorista, on_delete=models.CASCADE)
    vehiculo = models.ForeignKey(Vehiculo, on_delete = models.CASCADE)
    carga = models.OneToOneField(Carga, on_delete=models.CASCADE)
    aduana_destino= models.ForeignKey(Aduana, on_delete=models.PROTECT,null=True)
    tipo_de_viaje= models.CharField(max_length=20)
    empresa_dueña=models.ForeignKey("Empresa", on_delete=models.PROTECT)
    validacion_llave= models.ForeignKey("Validacion",on_delete=models.CASCADE, blank=True, null=True)

    def __str__(self) -> str:
        return "numero registro: {}".format(self.numero_registro)


class Validacion(models.Model):
    estado_validacion=models.CharField(max_length=50)#validado denegado en proceso)
    fecha_validacion= models.DateField(blank=True,null=True)
    aduana = models.ForeignKey(Aduana, on_delete=models.CASCADE, blank=True)
    registro_transito = models.OneToOneField(RegistroTransito, on_delete=models.PROTECT)

class TipoValidacion(models.Model):
    tipo_validacion=models.CharField(max_length=45)

    def __str__(self) -> str:
        return "{}".format(self.tipo_validacion)

class DetalleRegistroValidacion(models.Model):
    validacion= models.ForeignKey(Validacion,on_delete=models.PROTECT)
    tipo_validacion=models.ForeignKey(TipoValidacion, on_delete=models.PROTECT)
    descripcion_validacion=models.CharField(max_length=250)

class AduanaUsuario(models.Model):
    aduana_id=models.ForeignKey(Aduana,on_delete=models.PROTECT)
    usuario_sistema_id= models.ForeignKey(UsuarioSistema,on_delete=models.PROTECT)

SistemaDeControlAduanero/gestionTransporte/views.py
from datetime import datetime
from xml.dom import ValidationErr
from django.contrib import messages
from django.forms import EmailField
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.views.decorators.csrf import csrf_protect 
from django.shortcuts import redirect, render
from django.contrib.auth import login, logout,authenticate
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from .models import *
from .forms import *

def index(request):
    return render(request, 'gestionTransporte/index.html')

@login_required
def registrarVehiculo(request):
    if request.user.rol=="empresa":
        empresaVehiculo = Empresa.objects.get(usuario_sistema=UsuarioSistema.objects.get(username=request.user))
        vehiculos = Vehiculo.objects.filter(empresa=empresaVehiculo)
        if(request.method == 'POST'):
            formularioVehiculo = FormularioVehiculo(request.POST)
            if formularioVehiculo.is_valid():
                formVehiculo = formularioVehiculo.cleaned_data
                if Vehiculo.objects.filter(placa=formVehiculo['placa']).exists():
                    messages.error(request,'La placa ya está registrada')
                else:
                    vehiculo = Vehiculo()
                    vehiculo.marca = formVehiculo['marca']
                    vehiculo.modelo = formVehiculo['modelo']
                    vehiculo.placa = formVehiculo['placa']
                    vehiculo.anio = formVehiculo['anio']
                    vehiculo.motor = formVehiculo['motor']
                    vehiculo.chasis= formVehiculo['chasis']
                    vehiculo.num_ejes = formVehiculo['num_ejes']
                    vehiculo.capacidad = formVehiculo['capacidad']
                    #vehiculo.estado = False
                    vehiculo.empresa = empresaVehiculo
                    vehiculo.save()
                return redirect('/registrarVehiculo')
            else:
                return render(request,'gestionTransporte/registrarVehiculo.html',{"formularioVehiculo":formularioVehiculo,"vehiculos":vehiculos})
        else:
            formularioVehiculo = FormularioVehiculo()
            return render(request, 'gestionTransporte/registrarVehiculo.html',{"formularioVehiculo":formularioVehiculo,"vehiculos":vehiculos})
    elif request.user.rol=="aduana":
        return redirect('/gestionAduana')

def eliminarVehiculo(request,id):
    vehiculo = Vehiculo.objects.get(id=id)
    vehiculo.delete()
    return redirect('/registrarVehiculo')

def edicionVehiculo(request,id):
    vehiculo = Vehiculo.objects.get(id=id)
    return render(request, 'gestionTransporte/vehiculo.html',{"vehiculo":vehiculo})

def editarVehiculo(request):
    marca = request.POST['txtMarca']
    motor= request.POST['txtmotor']
    modelo = request.POST['txtModelo']
    chasis = request.POST['txtChasis']
    placa = request.POST['txtPlaca']
    ejes = request.POST['txtEjes']
    anio = request.POST['txtYear']
    capacidad = request.POST['txtCapacidad']

    vehiculo = Vehiculo.objects.get(id=request.POST['txtId'])
    vehiculo.marca = marca
    vehiculo.motor = motor
    vehiculo.modelo = modelo
    vehiculo.chasis = chasis
    vehiculo.placa = placa
    vehiculo.num_ejes = ejes
    vehiculo.anio = anio
    vehiculo.capacidad = capacidad
    vehiculo.save()
    return redirect('/registrarVehiculo')

@login_required 
def registrarMotorista(request):
    empresaMotorista = Empresa.objects.get(usuario_sistema=UsuarioSistema.objects.get(username=request.user))
    motoristas = Motorista.objects.filter(empresa=empresaMotorista)
    #select_sexo= Sexo.objects.all()
    #empresaMotorista.objects.filter()
    if(request.method=='POST'):
        formularioMotorista = FormularioTransportista(request.POST)
        if formularioMotorista.is_valid():
            formMotorista = formularioMotorista.cleaned_data
            if Motorista.objects.filter(doc_identificacion=formMotorista['docIdentificacion']).exists():
                messages.error(request,'El transportista ya existe')
            elif Motorista.objects.filter(licencia = formMotorista['licencia']).exists():
                messages.error(request,'El transportista con esa licencia ya existe')
            else:
                motorista = Motorista()
                motorista.nombre = formMotorista['nombreTransportista']
                motorista.apellido = formMotorista['apellidoTransportista']
                motorista.doc_identificacion = formMotorista['docIdentificacion']
                motorista.licencia = formMotorista['licencia']
                motorista.sexo = formMotorista['sexo']
                motorista.empresa = empresaMotorista
                motorista.save()
            #return render(request, 'gestionTransporte/registrarMotorista.html')
            return redirect('/registrarMotorista')
        else:
            return render(request, 'gestionTransporte/registrarMotorista.html',{"formularioMotorista":formularioMotorista,"motoristas":motoristas}) 
    else:
        formularioMotorista = FormularioTransportista()
        return render(request, 'gestionTransporte/registrarMotorista.html',{"formularioMotorista":formularioMotorista,"motoristas":motoristas})

def eliminarMotorista(request,id):
    motorista= Motorista.objects.get(id=id)
    motorista.delete()
    return redirect('/registrarMotorista')

def edicionMotorista(request,id):
    motorista  = Motorista.objects.get(id=id)
    selectSexo = Sexo.objects.all()
    return render(request, 'gestionTransporte/motorista.html',{"selectSexo":selectSexo,"motorista":motorista})

def editarMotorista(request):
    motorista = Motorista.objects.get(id=request.POST['txtId'])
    
    nombre = request.POST['txtNombre']
    apellido = request.POST['txtApellido']
    documento = request.POST['txtDoc']
    licencia = request.POST['txtLic']
    sexo = Sexo.objects.get(id=request.POST['txtSexo'])

    motorista.nombre = nombre
    motorista.apellido= apellido
    motorista.doc_identificacion = documento
    motorista.licencia = licencia
    motorista.sexo = sexo
    motorista.save()
    return redirect('/registrarMotorista')


@csrf_protect 
@login_required
def registrarManifiestoCarga(request):
    mensaje_error=""
    fecha_ahora= datetime.today().strftime("%Y-%m-%d")
    registros_actuales=RegistroTransito.objects.all()
    numero_registro= len(registros_actuales)+1
    motoristas_disponibles= Motorista.objects.filter(empresa_id=
    Empresa.objects.get(usuario_sistema_id=request.user.id).id
    ).filter(estado_motorista=True)
    vehiculos_diponibles=Vehiculo.objects.filter(
        empresa_id= Empresa.objects.get(usuario_sistema_id= request.user.id).id
    ).filter(estado=True)
    empresa_dueña=Empresa.objects.get(usuario_sistema_id=request.user.id)
    pais_empresa=Pais.objects.get(id=empresa_dueña.pais_id)
    if request.method=='POST':
        formulario= FormularioRegistroTransito(request.POST)
        temp_motorista= request.POST['motorista']
        temp_vehiculo=request.POST['vehiculo']
        if temp_motorista!=" " and temp_vehiculo!=" ":
            motorista_temporal= Motorista.objects.get(id=temp_motorista)
            vehiculo_temporal= Vehiculo.objects.get(id=temp_vehiculo)
            if formulario.is_valid():
                datos_form= formulario.cleaned_data
                fecha_arribo= datos_form["fecha_destino"]
                if formulario.validar_fechas(datetime.now().date(),fecha_arribo):
                    pais_consignatario=datos_form["pais_consignatario"]
                    tipo_viaje= formulario.definir_tipo_viaje(pais_empresa,pais_consignatario)
                    carga_viaje= Carga(tipo=datos_form["tipo_carga"],
                                       descripcion=datos_form["descripcion_carga"],
                                       peso=datos_form["peso"])
                    carga_viaje.save()
                    motorista_temporal.estado_motorista=False
                    vehiculo_temporal.estado=False
                    motorista_temporal.save()
                    vehiculo_temporal.save()
                    registro_viaje= RegistroTransito(numero_registro=numero_registro,
                                                     origen=datos_form["origen"],
                                                     pais_consignatario=datos_form["pais_consignatario"],
                                                     fecha_destino=datos_form["fecha_destino"],
                                                     motorista=motorista_temporal,
                                                     vehiculo=vehiculo_temporal,
                                                     carga=carga_viaje,
                                                     aduana_destino=datos_form["aduana_destino"],
                                                     tipo_de_viaje=tipo_viaje,
                                                     empresa_dueña=empresa_dueña,
                                                     validacion_llave=None)
                    registro_viaje.save()
                    validacion_regsitro= Validacion(
                        estado_validacion='proceso',
                        fecha_validacion=None,
                        aduana= datos_form['aduana_destino'],
                        registro_transito=registro_viaje,
                    )
                    validacion_regsitro.save()
                    registro_viaje.validacion_llave=validacion_regsitro
                    registro_viaje.save()
                    return redirect('gestionTransporte:inicioEmpresa')
                else:
                    mensaje_error="La fecha de arribo no puede ser antes que la fecha actual"
                    return render(request,'gestionTransporte/registroManifiesto.html',

SistemaDeControlAduanero/gestionTransporte/templates/gestionTransporte/detalle_validacion.html
{% extends "gestionTransporte/base.html" %}
{% load static %}
{% block content %}
<h1>Detalles de validacion</h1>
<!--Datos de documento de validacion-->   
{% csrf_token %}
<table class="table table-sm formulario_2" rules=all border=5>
    {% csrf_token %}
    <thead>
        <th><label class="form-label mt-4">Estado validacion</label></th>
        <th><label class="form-label mt-4">fecha validacion</label></th>
        <th><label class="form-label mt-4">Aduana</label></th>
        <th><label class="form-label mt-4">Guardar cambios</label></th>
    </thead>
    {% csrf_token %}
    <tr>
        {% csrf_token %}
        <form action="" method="post" id="formulario_validacion_1" name="formulario_validacion_1">
            {% csrf_token %}
        <td>{{formulario_validacion.estado_validacion}}</td>
        <td>{{formulario_validacion.fecha_validacion}}</td>
        <td>{{formulario_validacion.aduana}}</td>
        <td><input type="submit" value="guardar cambios" class="btn btn-outline-dark"></td>
    </form>
    </tr>
</table>



<h1>Agregar observaciones</h1>


<table class="table table-sm formulario_1" rules=all border=5>
    <tr>
        <td colspan="2"><h5>Observaciones motoristas</h5></td>
    </tr>
    <tr>
        <td>
            <table class="table table-sm">
                <thead>
                    <th>Seleccione un dato</th>
                    <th>Dato</th>
                </thead>
                    <tr><td><label class="form-label mt-4">Nombre</label></td><td><label class="form-label mt-4">{{motorista.nombre}}</label></td></tr>
                    <tr><td><label class="form-label mt-4">Apellido</label></td><td><label class="form-label mt-4">{{motorista.apellido}}</label></td></tr>
                    <tr><td><label class="form-label mt-4">Doc_identifiacion</label></td><td><label class="form-label mt-4">{{motorista.doc_identificacion}}</label></td></tr>
                    <tr><td><label class="form-label mt-4">Licencia</label></td><td><label class="form-label mt-4">{{motorista.licencia}}</label></td></tr>
            </table>
        </td>
        <td rowspan="4">
            {% csrf_token %}
            <form action="" method="post" style="text-align:center;">
                {% csrf_token %}
               <table class="table">
                <tr><b>Tipo validacion:</b><input type="text" name="tipo_validacion" id="tipo_validacion" value="transportista" readonly=true class="form-control-plaintext" style="width:75%; display:inline;padding-left: 12%;"></tr>
                {{formulario.as_table}}
               </table>
               <input type="submit" class="btn btn-outline-dark" value="agregar observacion" style="width: 50%; margin-bottom: 5px;"></input>
            </form>
            {% if observaciones_motorista %}
            <ul class="list-group">
                {% for observacion in observaciones_motorista %}
                <li class="list-group-item d-flex justify-content-between align-items-center">
                    {{observacion.descripcion_validacion}}
                  <span class="badge rounded-pill bg-dark"><a href="{% url 'gestionTransporte:eliminar_observacion' observacion.id %}">eliminar</a></span>
                </li>
                {% endfor %}
              </ul>
            {% endif %}
        </td>
    </tr>
</table>

<!--Tabla para validacion de vehiculo-->
<table class="table table-sm formulario_1" rules=all border=5>
    <tr>
        <td colspan="2"><h5>Observaciones Vehiculo</h5></td>
    </tr>
    <tr>
        <td>
            <table class="table table-sm">
                <thead>
                    <td>Dato</td>
                    <td>Valor</td>
                </thead>
                    <tr><td><label class="form-label mt-4">Placa</label></td><td><label class="form-label mt-4">{{vehiculo.placa}}</label></td></tr>
                    <tr><td><label class="form-label mt-4">Modelo</label></td><td><label class="form-label mt-4">{{vehiculo.modelo}}</label></td></tr>
                    <tr><td><label class="form-label mt-4">Chasis</label></td><td><label class="form-label mt-4">{{vehiculo.chasis}}</label></td></tr>
                    <tr><td><label class="form-label mt-4">Motor</label></td><td><label class="form-label mt-4">{{vehiculo.motor}}</label></td></tr>
            </table>
        </td>
        <td rowspan="4">
            {% csrf_token %}
            <form action="" method="post" style="text-align:center;">
                {% csrf_token %}
               <table class="table">
                <tr><b>Tipo validacion:</b><input type="text" value="vehiculo" readonly=true class="form-control-plaintext" style="width:75%; display:inline;padding-left: 12%;" name="tipo_validacion" id="tipo_validacion"></tr>
                {{formulario.as_table}}
               </table>
               <input type="submit" class="btn btn-outline-dark" value="agregar observacion" style="width: 50%; margin-bottom: 5px;"></input>
            </form>
            {% if observaciones_vehiculo %}
            <ul class="list-group">
                {% for observacion in observaciones_vehiculo %}
                <li class="list-group-item d-flex justify-content-between align-items-center">
                    {{observacion.descripcion_validacion}}
                  <span class="badge rounded-pill bg-dark"><a href="{% url 'gestionTransporte:eliminar_observacion' observacion.id %}">eliminar</a></span>
                </li>
                {% endfor %}
              </ul>
            {% endif %}
        </td>
    </tr>
</table>

<!--Tabla para validar carga-->
<table class="table table-sm formulario_1" rules=all border=5>
    <tr>
        <td colspan="2"><h5>Observaciones Carga</h5></td>
    </tr>
    <tr>
        <td>
            <table class="table table-sm">
                <thead>
                    <td>Dato</td>
                    <td>Valor</td>
                </thead>
                    <tr><td><label class="form-label mt-4">Tipo</label></td><td><label class="form-label mt-4">{{carga.tipo}}</label></td></tr>
                    <tr><td><label class="form-label mt-4">Descripcion</label></td><td><label class="form-label mt-4">{{carga.descripcion}}</label></td></tr>
                    <tr><td><label class="form-label mt-4">Peso</label></td><td><label class="form-label mt-4">{{carga.peso}} KG</label></td></tr>
            </table>
        </td>
        <td rowspan="4">
            {% csrf_token %}
            <form action="" method="post" style="text-align:center;">
                {% csrf_token %}
               <table class="table">
                <tr><b>Tipo validacion:</b><input type="text" value="carga" readonly=true class="form-control-plaintext" style="width:75%; display:inline;padding-left: 12%;" name="tipo_validacion" id="tipo_validacion"></tr>
                {{formulario.as_table}}
               </table>
               <input type="submit" class="btn btn-outline-dark" value="agregar observacion" style="width: 50%; margin-bottom: 5px;"></input>
            </form>
            {% if observaciones_carga %}
            <ul class="list-group">
                {% for observacion in observaciones_carga %}
                <li class="list-group-item d-flex justify-content-between align-items-center">
                    {{observacion.descripcion_validacion}}
                  <span class="badge rounded-pill bg-dark"><a href="{% url 'gestionTransporte:eliminar_observacion' observacion.id %}">eliminar</a></span>
                </li>
                {% endfor %}
              </ul>
            {% endif %}
        </td>
    </tr>
</table>
<div id="caja_prueba" name="caja_prueba">

</div>
<a href="{% url 'gestionTransporte:trasnporte_list' idAduana %}" class="btn btn-outline-dark">Terminar observaciones</a>
{% endblock %}

{% block extrajs %}
function poner_valor(){
    let documento= document.getElementById('nombre_check')
    if documento.value==true{
        document.getElementById("caja_prueba").innerHTML= "si funciona el checkbox"
    }
}
{% endblock extrajs %}
<!--la esperanza y confianza en nosotros mismos esta determinada
en gran medida en la esperanza y confianza que tenemos en el resto de nuestros
projimos-->

SistemaDeControlAduanero/gestionTransporte/templates/gestionTransporte/gestionAduana.html
{% extends "gestionTransporte/base.html" %}
{% load static %}
{% block content %}
<div class="container" id="gestionAduana">
    <h2>Elegir aduana</h2>

    <div class="container">
      <div class="row">



          {%for user in aduanas%}

          <div class="card text-white bg-primary mb-3" style="max-width: 20rem; margin: 5px;">
            <div class="card-header">{{user.aduana_id.id}}</div>
            <div class="card-body">
              <h4 class="card-title">{{user.aduana_id.nombre}}</h4>
              
            </div>
            <div class="card-footer">
              <a class="btn text-light badge rounded-pill bg-info" href="../../listadoRegistroTransporte/{{user.aduana_id.id}}">Gestionar</a>
            </div>
          </div>

        {%endfor%}
      </div>
    </div>
                  
  </div>
</div>
{% endblock %}

SistemaDeControlAduanero/gestionTransporte/templates/gestionTransporte/login.html
    {% extends "gestionTransporte/base.html" %}
    {% load static %}
    {% block content %}
        <div class="container" id="container_login">
            <h1>Iniciar sesion</h1>
        <form action="" method="POST">
            {% csrf_token %}
            <table class="table">
                {%if messages%}  
                    {% for mensaje in messages %}
                    <div class="alert alert-danger">
                        {{mensaje}}
                    </div>
                    {% endfor %}
                {% endif %}
                {{ formulario.as_table }}
            </table>
            <input type="submit" value="iniciar sesion" class="btn btn-primary">
            <!--agrega un boton que haga referencia a la pagina de registro de usuario-->
            <a href="{% url 'gestionTransporte:registroUsuario' %}" class="btn btn-primary">Registrar Usuario</a>
        </form>
        </div>
        
    {% endblock %}

SistemaDeControlAduanero/gestionTransporte/templates/gestionTransporte/ver_registro.html
    <div class="modal-dialog" role="document">
      <div class="modal-content" tabindex="1">
        <div class="modal-header">
          <h5 class="modal-title">Registro hecho</h5>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close">
            <span aria-hidden="true"></span>
          </button>
        </div>
        <div class="modal-body">
          <p>{{registro.numero_registro}}</p>
          <p>{{registro.vehiculo}}</p>
          <p>{{registro.motorista}}</p>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-primary">Save changes</button>
          <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
        </div>
      </div>
    </div>